### PR TITLE
Add support for recursive models

### LINKED ISSUE #110: Add support for recursive nested models
**Is your feature request related to a problem? Please describe.**
Currently, `flask-restx` swagger.json generation breaks when one defines some models with recursive/circular references to one another. See noirbizarre/flask-restplus#190

**Describe the solution you'd like**
A PR was made in the `flask-resplus` repo that fixes the issue: noirbizarre/flask-restplus#656

### PR DESCRIPTION
**Pull request by peterjwest**
This is a port of https://github.com/noirbizarre/flask-restplus/pull/656
It should resolve #110 

Thanks to @buggyspace, @drarok and @edwardfung123 for identifying and fixing this.

I've followed the CONTRIBUTING.rst file, but couldn't locate the changelog to add this change, is this out of date?

### CODE REVIEW

**Comment by peterjwest** [comment]
@ziirish is there any chance you could review this?

**Comment by peterjwest** [comment]
Does this need to be rebased before it can be merged?

**Comment by j5awry** [comment]
@peterjwest yes, if you could give this a rebase. I'm giving my +1 as well, so we'll be able to merge after rebase.

**Comment by peterjwest** [comment]
@j5awry done

**Pull request merged**
