### PR TITLE
Fix Issue #164: generate choices schema without collectionFormat

### PR DESCRIPTION
**Pull request by leopold-p**

### CODE REVIEW

**Comment by leopold-p** [comment]
i have no idea what coverage wants from me

**Comment by peterjwest** [comment]
By removing a line of code, you've technically reduced the coverage percentage, so annoyingly, to make this pass you'd need to add a test that adds a new line of coverage, or make some code take more lines than it used to 😅

**Comment by leopold-p** [comment]
Do we have to do codecov's bidding in obvious cases like this? Adding lines of code just to please a tool is insane.

**Comment by peterjwest** [comment]
I agree with you, but I'm not associated with this project, sorry!

**Comment by ziirish** [comment]
Hello,

No problem for the "coverage failure".
But this PR clearly lacks some context.

What are you trying to solve?
Why?
etc.

This is explained in our [CONTRIBUTING](https://github.com/python-restx/flask-restx/blob/master/CONTRIBUTING.rst#submitting-patches-bugfix-features-) guidelines.

**Comment by peterjwest** [comment]
@ziirish the commits reference a bug originally raised in flask restplus:
https://github.com/noirbizarre/flask-restplus/issues/488

**Comment by ziirish** [comment]
Oh yes, my bad. I overlooked the commit messages.

**Pull request merged**
