### PR TITLE
Upgrade swagger ui to 3.48.0

### LINKED ISSUE #300: tryItOutEnabled
**Is your feature request related to a problem? Please describe.**
To explore my API I always have to click try it out. This consumes quite some time

**Describe the solution you'd like**
Add an option to enable the try it out feature by default. This seems already possible in swagger via the tryItOutEnabled setting.
https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md

**Describe alternatives you've considered**
Hack the library similar to https://github.com/kristleifur/flask-restplus/commit/7896401427406a5ca78431066f33d579ca1d2d0d

**Additional context**
To avoid additional feature requests of this kind in the future, one might establish a way to pass everything that is listed in 
https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md

### PR DESCRIPTION
**Pull request by xuhdev**
Close #300

### CODE REVIEW

**Comment by xuhdev** [comment]
I have verified that this upgrade works and solves #300.

**Comment by j5awry** [comment]
@physikerwelt would you have the ability to test his proposed fix for #300?

**Comment by xuhdev** [comment]
@physikerwelt Would you mind testing it out :)

**Comment by xuhdev** [comment]
Could you help review and consider merging it, please? We are also waiting for the fix on our side and would like to avoid using a fork if possible. Thanks!

**Comment by physikerwelt** [comment]
Yes, I can certainly test it. I am not exactly sure how, but I will figure it out.

**Comment by physikerwelt** [comment]
It works nicely with
http://127.0.0.1:5000/?tryItOutEnabled=true
Is there any way to enable this option permanently on the server side?

**Comment by physikerwelt** [comment]
> Yes, I can certainly test it. I am not exactly sure how, but I will figure it out.

Thanks to @ziirish I manged to test it. [Thank you.](https://github.com/python-restx/flask-restx/issues/300#issuecomment-847822916)

**Review by j5awry — APPROVED** [review]

**Comment by xuhdev** [comment]
Thanks @physikerwelt ! You should be able to enable it by default by configuring it in `swagger-config.yaml` or environment variables: https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/

**Comment by xuhdev** [comment]
Could you make a new release :) Thanks!

**Comment by xuhdev** [comment]
Could you make a new release for this PR? Installing from the git repo won't get the new swagger UI version :( Thanks!

**Pull request merged**
