### PR TITLE
Added specs-url-scheme option for Api.

### PR DESCRIPTION
**Pull request by DustinMoriarty**
* Support explicitly setting the scheme for specs_url for the swagger.json file for cases where the URL scheme does not resolve correctly such as when deploying on AWS ECS behind an elastic load balancer. Behavior is unchanged for cases where the keyword argument is left as None. See https://github.com/python-restx/flask-restx/issues/237
* Added tests for the new behavior as well as to confirm the old behavior has not changed.
* Added docstrings.
* Formatted with black. This will effect the diff for a few other modules such as flask_restx/reqparse.py, flask_restx/model.py. flask_restx/inputs.py and some other locations in api.py.
* Added .python-version and .idea to .gitignore.

### CODE REVIEW

**Review by mas15 — APPROVED** [review]

**Comment by DustinMoriarty** [comment]
@mas15 or @j5awry : This fails on code coverage.  However, if you look at the files changed and the code coverage report, I don't think that the results are meaningful. The file with decreased coverage is not even one that was changed by this PR. Is there any way to override the failed check?

**Comment by DustinMoriarty** [comment]
@mas15 OR @j5awry : Can this be merged? Thank you.

**Comment by mas15** [comment]
@DustinMoriarty Hi, I cannot do that since I am not a maintainer. This project is abandoned and I would not expect this to be merged

**Comment by DustinMoriarty** [comment]
To bad.  Thanks for letting me know.

**Comment by DustinMoriarty** [comment]
@j5awry : I updated this to get it up to date with the upstream. I do need maintainer approval to get it through the workflow checks and merge if you think this is something you would like to do.

**Review by j5awry — APPROVED** [review]
Thanks for your contribution, and for taking the time to update this after we moved ahead! LGTM

**Pull request merged**
