### PR TITLE
fix: flask import of _endpoint_from_view_func - issue #567

### PR DESCRIPTION
**Pull request by Ryu-CZ**
Due to repeated accident of import error #567 I added helper method _import_check_view_func_ . With fallback to last known implementation which stayed the same in all flask versions.

I submit new pull request with new branch name `flask-scaffold_567` on same commit, because in original pull request #568  I used `master` branch in contrary to guidelines.

### CODE REVIEW

**Comment by peter-doggart** [comment]
Thanks for doing this @Ryu-CZ 

I'm assuming this is held up by the `pytest-flask` issue?

**Comment by Ryu-CZ** [comment]
@peter-doggart yes, tests are not passing because `pytest-flask` issue [167](https://github.com/pytest-dev/pytest-flask/issues/167)

**Comment by Ryu-CZ** [comment]
I forgot to add my method into `utils.__all__`  so here is small patch to fix it. This should prevent static syntax analyses to show weak warning about Importing method not listed in __all__.

**Comment by peter-doggart** [comment]
Still waiting on the pytest fixes, but it looks like they are working on getting that project updated. :)

**Comment by Ryu-CZ** [comment]
I forget to mention the new method `import_check_view_func` to get `_endpoint_from_view_func` is compatible with `flask` reasonable versions 1, 2, 3.

**Pull request merged**
