### PR TITLE
Housekeeping: Remove traces of python2.7

### PR DESCRIPTION
**Pull request by Poogles**
As above.  Might be worth us setting up CI before this gets merged, everything passes locally but that never fills me with confidence...

There's a few places where I've started removing 3.4 support as well (check Tox/setup.py).  Can remove these if required but if not I'll add another PR later finishing removing 3.4 support.

### CODE REVIEW

**Comment by SteadBytes** [comment]
@Poogles thanks for this, however as discussed in Gitter the **first** release of the new fork *will* be keeping the Python 2 support. This is just to enable existing users (if there are any) to receive the bugfixes that were meant to be part of the Flask-RESTPlus 0.14.0 release that we were unable to publish due to @noirbizarre's absence. Removal of Python2 will come in the next release of `flask-restx` I think :smile:

**Comment by Poogles** [comment]
@SteadBytes yeah that's fine, I can't see any of this PR going stale anytime soon.

**Comment by SteadBytes** [comment]
It might have some fun conflicts after https://github.com/python-restx/flask-restx/pull/2 is merged. We shall have to see :sweat_smile:

**Comment by Poogles** [comment]
I'll rebase this after lunch ^^

**Comment by SteadBytes** [comment]
@poogles I really appreciate your enthusiasm! But there's no rush on this - we're not ready for the first release yet and are yet to plan and prioritise work for the subsequent release (of which this may be part of) 😊

**Comment by j5awry** [comment]
As we thought, tons of conflicts post merging #2. We did our first release, so we can put this to the top of the stack again.

**Comment by SVilgelm** [comment]
@Poogles It's a good time to continue this work 👍

**Comment by ziirish** [comment]
@Poogles we are now ready to move forward with this change. Would you have a chance to continue your work?
If you don't have time anymore we can also take it from here, just let us know what you prefer.

Thanks

**Comment by ziirish** [comment]
FYI, I'll continue the work from here.
Thanks @Poogles for all you've done so far!

**Comment by ziirish** [comment]
closing this PR in favor of #113

**Pull request closed without merging**
