### PR TITLE
The Flask/Blueprint API moved to the Scaffold base class

### PR DESCRIPTION
**Pull request by jloehel**
Changed in: https://github.com/pallets/flask/commit/b146a13f633b0e2e26e3b8383b3db0feb563bc83

Fixes: #308

Signed-off-by: Jürgen Löhel <juergen.loehel@inlyse.com>

### CODE REVIEW

**Review by j5awry — APPROVED** [review]
Approved. waiting on passing tests.

**Comment by j5awry** [comment]
Hm...this errors need looked into. At the same time, I don't think they're specifically related to this PR. I'll have to dig in a little bit and see what's happening here...

**Comment by andreykurilin** [comment]
@j5awry hi!
The issue relates to the recently released werkzeug that contains https://github.com/pallets/werkzeug/issues/1758 . Instead of calling inner helper method that handled `None` description, werkzeug switched to use `html.escape`.

There is also new related issue - https://github.com/pallets/werkzeug/issues/2115

**Comment by j5awry** [comment]
@andreykurilin Thanks! I was just getting up to check on all this, and hit re-run to see if it was ephemeral. 

I'm leaning towards setting flask-restx to 

```
flask >=0.8, <2.0.0
werkzeug <2.0.0
```

at least until those stabilize a bit.

**Comment by ziirish** [comment]
@j5awry I'd do the same as well.
We have a pending work on dropping support for python <=3.5 we could finish this and work on integrating Flask >=2.0 in a future release.

**Comment by j5awry** [comment]
related PR is up to pin versions: 

https://github.com/python-restx/flask-restx/pull/311

Once tests pass there, confirming issues here are dependency related, i'll pull this in as well, then cut a release.

**Pull request merged**
