### PR TITLE
fix: Incorrect location type in swagger when multi locations used

### LINKED ISSUE #82: Setting multiple locations for a parameter in reqparser breaks it
Just encountered the following bug: https://github.com/noirbizarre/flask-restplus/issues/520

Documentation still says multiple locations are supported (https://flask-restx.readthedocs.io/en/stable/parsing.html#multiple-locations)

Relevant to discussion on https://github.com/python-restx/flask-restx/issues/59

### PR DESCRIPTION
**Pull request by tomduval**
A quick fix for an annoying bug where multiple locations cause the swagger documentation to just show "query" instead of either of the locations specified.

Fixes #82

### CODE REVIEW

**Comment by tomduval** [comment]
https://github.com/python-restx/flask-restx/blob/9b62319e6999de44c686b669bbba40363a95c61c/flask_restx/reqparse.py#L85-L87

This is actually the desired result from the docstring.

**Comment by j5awry** [comment]
@tomduval Thank you for the contribution. Sorry for taking a while to take a look, and letting this get stale. If you could rebase and push or merge in master to get this from a stale state.

**Comment by tomduval** [comment]
@j5awry done

**Comment by tomduval** [comment]
Hi @j5awry - I'm going to leave this now - it's all taking way too long. I've actually switched to FastAPI. Would highly recommend having a look - it's a great framework for APIs. Thanks!

Feel free to close this pull request.

**Comment by SteadBytes** [comment]
Sorry to see you go @tomduval but thank you for the contribution anyway. The `flask-restx` team has been unfortunately "under staffed" lately, I hope you find FastAPI solves your problems!

**Pull request closed without merging**
